Add proofcast adapter
gnosis/hashi pull request #60
Opened 2024-06-04 13:55 UTC by gitmp01

Add the Proofcast adapter, which expects the `MessageDispatched` event signed with the event attestator component.

2024-06-11 05:05 UTC, allemanfredi requested changes

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +    uint256 public constant TEE_ADDRESS_CHANGE_GRACE_PERIOD = 172800; // 48 hours
you can write `48 hours`

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +    error InvalidEventRLP();
can you add the variable names?

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +contract ProofcastAdapter is BlockHashAdapter, MessageIdCalculator, MessageHashCalculator, Ownable {
Move the event and error declarations under the variable declarations

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +        require(chainId != block.chainid, "Not usable Yaho (same chainId)");
Please use custom errors instead of `require`

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +        require(teeAddress != address(0), "Tee signer not set!");
same ...

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +        require(ECDSA.recover(sha256(statement), signature) == teeAddress, "Invalid signature");
same ...

2024-06-11 05:05 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +        (ids, hashes) = abi.decode(message.data, (uint256[], bytes32[]));
`message.data` doesn't contain the `messageIds` and the `hashes`. `message.data` is just the abitrary data that is sent cross-chain. 

```sol
messageHash = calculateMessageHash(message)
messageId = calculateMessageId(chainId, yahoAddress, messageHash)
ids[0] = messageId
hashes[0] = messageHash
```

2024-06-18 05:48 UTC, allemanfredi requested changes
lgtm! just one small change

2024-06-18 05:48 UTC, allemanfredi commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +    function applyNewTeeSigner() public {
make it external

2024-06-18 08:13 UTC, gitmp01 commented on packages/evm/contracts/adapters/Proofcast/ProofcastAdapter.sol
> +    function applyNewTeeSigner() public {
done!

2024-09-24 14:19 UTC, closed without merging